name = "orbit-focus"
main = "api/cloudflare/index.ts"
compatibility_date = "2025-12-01"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[dev]
port = 8787

[[d1_databases]]
binding = "orbit_focus_db"
database_name = "orbit_focus_db"
database_id = "0d7f487a-8a28-4a42-8fd2-635f7582e536"

[vars]
NODE_ENV = "production"
